POST https://asia-northeast1-superfarmers.cloudfunctions.net/Insert
Content-Type: application/json

{
  "uuid": "756e6b776f000c04",
  "temperature": 28,
  "humidity": 61,
  "pH": 5.8,
  "ec": 1.1,
  "light": 70,
  "liquid_temperature": 25,
  "liquid_level": false,
  "led": true,
  "fan": false
}
